### PR TITLE
Ready for Review

### PR DESCRIPTION
**Pull request by Morrism1**
- Loaded data from OpenWeatherMap API
- Created a search feature
- Displayed the data from search to corresponding elements
- Added the toggle for the temperature changing 

[Live Demo](https://awesome-ptolemy-d840b3.netlify.app/)

### CODE REVIEW

**Review by NtwaliHeritier — CHANGES_REQUESTED** [review]
### **STATUS: CHANGES REQUESTED🛑🛑**
Hello @Morrism1 , great work on the project. I love the overall design and it is working flawlessly.
Make a small change and let's make the PR approved.

[REQUESTED]: Add specifications on how to install the project locally.

That's it
giphy (2)

Make the changes and ask for another review.👌👌

**Comment by Morrism1** [comment]
> ### **STATUS: CHANGES REQUESTED🛑🛑**
> Hello @Morrism1 , great work on the project. I love the overall design and it is working flawlessly.
> Make a small change and let's make the PR approved.
> 
> [REQUESTED]: Add specifications on how to install the project locally.
> 
> That's it
> giphy (2)
> 
> Make the changes and ask for another review.👌👌

Thanks, @NtwaliHeritier for the review. I made the changes 😁

**Review by MahmoudBakr23 — APPROVED** [review]
# **Approved ✔✔**

<hr>

Hello there, great job you've done so far on this project, I like your organized code, and the extra feature you've added to the project. Congratulations 🎉🎉You may now merge and submit.

## **[OPTIONAL but recommended]**

- If you could take 5 mins of your time to add a displayed messages while errors or invalid names, it'd be super nice for the completion of your app. i.e. 
```
if (response.status === 404)
{
errorMsgs()
} else {
// current code goes here
}
```

**Comment by Morrism1** [comment]
> # **Approved ✔✔**
> Hello there, great job you've done so far on this project, I like your organized code, and the extra feature you've added to the project. Congratulations 🎉🎉You may now merge and submit.
> 
> ## **[OPTIONAL but recommended]**
> * If you could take 5 mins of your time to add a displayed messages while errors or invalid names, it'd be super nice for the completion of your app. i.e.
> 
> ```
> if (response.status === 404)
> {
> errorMsgs()
> } else {
> // current code goes here
> }
> ```

Thanks, @MahmoudBakr23 I am going to implement that. 👍

**Pull request merged**
